version: '3.8'

services:

  server:
    build:
      dockerfile: Dockerfile
      context: ./server
    container_name: server
    ports:
      - "6020:6020"
    restart: always
    networks:
      - server
    volumes:
      - .:/app/
      - /app/server/node_modules
    env_file:
      - ./server/.env
  nginx-proxy:
    build:
      dockerfile: Dockerfile
      context: ./server/proxy
    depends_on:
      - server
    networks:
      - server
    ports:
      - 80:80
networks:
  server:

# volumes:
#   mongodb_data_container: